import axios from 'axios'
import Head from 'next/head'
import { useState, useEffect } from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home({ parks }) {
  const [isLoading, setIsLoading] = useState(true);
  const [parkIndex, setParkIndex] = useState(1);
  const [selected, setSelected] = useState({
    image: parks.data[parkIndex].images[0].url,
    title: parks.data[parkIndex].fullName,
    parkCode:parks.data[parkIndex].parkCode
  });
  // const acadia = park.data[0];

  const handleChange = (e) => {
    setParkIndex(e.target.value);
  }

  useEffect(() => {
    if (parks.data) {
      setSelected({
        image: parks.data[parkIndex].images[0].url,
        title: parks.data[parkIndex].fullName,
        parkCode:parks.data[parkIndex].parkCode
      });
    }
  }, [parkIndex, parks.data]);

  useEffect(() => {
    if (parks.data) {
      setIsLoading(false);
    }
  }, [parks]);

  if (isLoading) {
    return <p>Loading...</p>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Link href="/">
          <a>My Next Park</a>
        </Link>
      </nav>

      <main className={styles.main}>
        <header>
          <h2 className={styles.title}>Find your Next Adventure</h2>
          <div>
            <div>{selected.title}</div>
            <div><img src={selected.image} alt={selected.title} height="150" width="150" /></div>
            <div>
              <label htmlFor="">Choose a park</label>
            </div>
            <div>
              <select name="" id="" onChange={handleChange}>{parks.data.map((park, idx) => {
                if(park.designation === 'National Park') {
                  return (<option key={park.id} value={idx}>{park.fullName}</option>)
                }
              })}</select>
              <Link href={`/parks/${selected.parkCode}`}>
                <button>Lets Go!!!</button>
              </Link>
            </div>
          </div>
          {/* <h2>{acadia.fullName}</h2> */}
        </header>
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  // 7hdKbKKAHL4liByqDtfoN93KpWGb0T7ClRwGagdJ
  const res = await axios.get(`https://developer.nps.gov/api/v1/parks?limit=500&api_key=${process.env.PARKS_API_KEY}`);
  const parks = res.data;

  return {
    props: {
      parks
    }
  }
}
